### ISSUE TITLE
BAC 판관비 용어 관련

### ISSUE THREAD

**Issue by changwoo-seo94** [light-src/toberich#10]
BAC의 손익계산서에 있던 거
Selling General and Administrative = General & Administrative Expense + Selling & Marketing Expense
인 듯 한데 야후파이낸스에 표시는 이렇게 돼 있고
데이터 자체는 Selling General and Administration으로 돼 있음

**Comment by light-src** [comment]
BAC를 보면 Web상에서는 아래와 같이 표시됨.
- Selling General and Administrative
- General & Administrative Expense 
- Selling & Marketing Expense

API에서는 아래와 같은 Key를 가지고 있음.
- Selling General And Administration
- Selling And Marketing Expense
- General And Administrative Expense

아래와 같은 우선순위로 계산하면 될듯.
- Selling General And Administration (판관비 합계)
- Selling And Marketing Expense (판매비) + General And Administrative Expense (관리비)
